import Head from "next/head";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { useAuth } from "../hooks/useAuth";
import styles from "../styles/Home.module.css";

// https://web.dev/sign-in-form-best-practices/
export default function SignIn() {
  const auth = useAuth();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    auth.signIn(email, password);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {auth.user ? (
          <>
            <h1 className={styles.title}>Signed in</h1>
            <button onClick={() => auth.signOut()}>Sign out</button>
          </>
        ) : (
          <>
            <h1 className={styles.title}>Sign in</h1>
            <form action="/" onSubmit={(e) => handleSubmit(e)}>
              <label htmlFor="email">Email</label>
              <input
                type="text"
                id="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <br />
              <label htmlFor="password">Password</label>
              <input
                type="password"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              <br />
              <button type="submit">Submit</button>
            </form>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
